import 'package:flutter/material.dart';

class AppIcons {
  static Map<String, dynamic> icones = {
    'sports_soccer': Icons.sports_soccer,
    'sports_baseball_outlined': Icons.sports_baseball_outlined,
    'sports_basketball': Icons.sports_basketball,
    'sports_volleyball': Icons.sports_volleyball,
    'sports_tennis': Icons.sports_tennis,
    'golf_course': Icons.golf_course,
    'sports': Icons.sports,
    'pool': Icons.pool,
    'fitness_center': Icons.fitness_center,
    'directions_bike': Icons.directions_bike,
    'outdoor_grill': Icons.outdoor_grill,
    'restaurant': Icons.restaurant,
    'restaurant_menu': Icons.restaurant_menu,
    'dining': Icons.dining,
    'free_breakfast': Icons.free_breakfast,
    'coffee': Icons.coffee,
    'local_bar': Icons.local_bar,
    'local_drink': Icons.local_drink,
    'breakfast_dining': Icons.breakfast_dining,
    'brunch_dining': Icons.brunch_dining,
    'lunch_dining': Icons.lunch_dining,
    'cake': Icons.cake,
    'event_seat': Icons.event_seat,
    'chair_alt': Icons.chair_alt,
    'table_bar': Icons.table_bar,
    'table_restaurant': Icons.table_restaurant,
    'weekend': Icons.weekend,
    'beach_access': Icons.beach_access,
    'storefront': Icons.storefront,
    'celebration': Icons.celebration,
    'terrain': Icons.terrain,
    'kitchen': Icons.kitchen,
    'pets': Icons.pets,
    'wifi': Icons.wifi,
    'directions_car': Icons.directions_car,
    'camera_alt': Icons.camera_alt,
    'tv': Icons.tv,
    'video_library': Icons.video_library,
    'hotel': Icons.hotel,
    'rule': Icons.rule,
    'check': Icons.check,
    'close': Icons.close,
    'do_not_disturb': Icons.do_not_disturb,
    'report': Icons.report,
    'error': Icons.error,
    'no_drinks': Icons.no_drinks,
    'no_meals': Icons.no_meals,
  };
}
